version: '3.7'
volumes:
    typebootdb: {}
    dsedb: {}
services:
    postgres:
      image: postgres:11.5
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=postgres
      ports:
        - "5432:5432"
      container_name: postgres
      networks:
        typebootn:
          aliases:
            - postgres

    dse:
      build: .
      image: dse-server:6.8.9-ubi7-tls
      environment:
        - DS_LICENSE=accept
        - SSL_VALIDATE=false
      ports:
        - "9042:9042"
      container_name: dse
      networks:
        typebootn:
          aliases:
            - dse
networks:
  typebootn: {}


      
