version: '3.7'
services:
  typeboot-spec-postgres:
    image: typeboot/typeboot-spec:0.7
    volumes:
      - ./output/postgres:/tmp/output
      - ./input/postgres:/tmp/input
      - ./postgres-spec.yaml:/opt/app/conf/.typeboot.yaml

  typeboot-spec-cassandra:
    image: typeboot/typeboot-spec:0.7
    volumes:
      - ./output/cassandra:/tmp/output
      - ./input/cassandra:/tmp/input
      - ./cassandra-spec.yaml:/opt/app/conf/.typeboot.yaml

networks:
  typebootn: {}


      
